const ACTIONS = {
    LOGIN: 'LOGIN',
    RELOAD: 'RELOAD',
    LOGOUT: 'LOGOUT',
    FETCH: 'FETCH',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    REGISTER: 'REGISTER',
    GETUSER: 'GETUSER',
    SEARCHROOM: 'SEARCHROOM',
    SEARCHSUCCESS: 'SEARCHSUCCESS',
    SEARCHFAILED: 'SEARCHFAILED',
    PAYMENTFETCH: 'PAYMENTFETCH',
    PAYMENTSUCCESS: 'PAYMENTSUCCESS',
    PAYMENTFAILED: 'PAYMENTFAILED',
};
export default ACTIONS;
